package loop

import (
	"encoding/json"
	"strings"
	"testing"
)

// RED tests for plan tool argument resilience (see .plans/PLAN_TOOL_ARG_RESILIENCE_PLAN.md).
// Failure taxonomy rows 1–5: each call must either succeed (coercion) or fail
// with a diagnostic that names the received keys so the model can correct in
// one retry.

// Row 1: wrong top-level key for steps → diagnostic error naming received keys.
func TestPlanCreate_WrongStepsKey_DiagnosticError(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","operations":[{"id":"s1","title":"One"}]}`)
	if err == nil {
		t.Fatal("expected error for create without steps, got success")
	}
	msg := err.Error()
	if !strings.Contains(msg, "steps") {
		t.Errorf("error should name the expected field 'steps', got: %s", msg)
	}
	if !strings.Contains(msg, "operations") {
		t.Errorf("error should name the unrecognized received key 'operations', got: %s", msg)
	}
}

// Row 2: steps nested under a single object key → unwrapped, inference noted.
func TestPlanCreate_NestedSteps_Unwrapped(t *testing.T) {
	store := NewPlanStore(12, 4000)
	res, err := store.Execute(`{"verb":"create","create":{"steps":[{"id":"s1","title":"One"}]}}`)
	if err != nil {
		t.Fatalf("nested steps should be unwrapped, got error: %v", err)
	}
	if !strings.Contains(res, "inferred") {
		t.Errorf("result should note the structural inference, got: %s", res)
	}
	if !strings.Contains(res, "One") {
		t.Errorf("plan should contain the step title, got: %s", res)
	}
}

// Row 3: step without id → auto-generated.
func TestPlanCreate_MissingStepID_AutoGenerated(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","steps":[{"title":"One"},{"title":"Two"}]}`)
	if err != nil {
		t.Fatalf("steps without ids should get auto-generated ids, got error: %v", err)
	}
	// Auto ids must be targetable by update/complete.
	if _, err := store.Execute(`{"verb":"complete","step_id":"s1"}`); err != nil {
		t.Errorf("auto id s1 should be addressable, got error: %v", err)
	}
}

// Row 3b: explicit ids preserved (no collision with auto ids).
func TestPlanCreate_MixedExplicitAndAutoIDs(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","steps":[{"id":"s2","title":"Explicit"},{"title":"Auto"}]}`)
	if err != nil {
		t.Fatalf("mixed explicit/auto ids should be accepted, got error: %v", err)
	}
	st, _ := store.Snapshot()
	if len(st.Steps) != 2 || st.Steps[0].ID != "s2" {
		t.Errorf("explicit id should be preserved, got %+v", st.Steps)
	}
}

// Row 4: step entry as bare string → coerced to title with auto id.
func TestPlanCreate_StringStepEntry_Coerced(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","steps":["Investigate","Fix"]}`)
	if err != nil {
		t.Fatalf("string step entries should coerce to titles, got error: %v", err)
	}
	st, _ := store.Snapshot()
	if len(st.Steps) != 2 || st.Steps[0].Title != "Investigate" {
		t.Errorf("string entries should become titles, got %+v", st.Steps)
	}
}

// Row 5: missing verb → diagnostic includes received keys.
func TestPlanExecute_MissingVerb_Diagnostic(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"steps":[{"id":"s1","title":"One"}]}`)
	if err == nil {
		t.Fatal("expected error for missing verb")
	}
	if !strings.Contains(err.Error(), "steps") {
		t.Errorf("error should mention received key 'steps', got: %s", err.Error())
	}
}

// Diagnostics extend to update/complete missing required fields.
func TestPlanUpdate_MissingUpdates_Diagnostic(t *testing.T) {
	store := NewPlanStore(12, 4000)
	if _, err := store.Execute(`{"verb":"create","steps":[{"id":"s1","title":"One"}]}`); err != nil {
		t.Fatal(err)
	}
	_, err := store.Execute(`{"verb":"update","changes":[{"id":"s1","status":"done"}]}`)
	if err == nil {
		t.Fatal("expected error for update without updates array")
	}
	if !strings.Contains(err.Error(), "changes") {
		t.Errorf("error should name received key 'changes', got: %s", err.Error())
	}
}

// Ambiguity stays a hard error: two candidate step arrays.
func TestPlanCreate_AmbiguousStepShapes_Rejected(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","steps":[{"id":"s1","title":"One"}],"operations":[{"id":"x","title":"X"}]}`)
	if err == nil {
		t.Fatal("ambiguous two-array input must be rejected")
	}
}

// Revise coercion: string step entries in add operations get auto ids.
func TestPlanRevise_StringStepEntry_Coerced(t *testing.T) {
	store := NewPlanStore(12, 4000)
	if _, err := store.Execute(`{"verb":"create","steps":[{"id":"s1","title":"One"}]}`); err != nil {
		t.Fatal(err)
	}
	_, err := store.Execute(`{"verb":"revise","reason":"add a step","operations":[{"kind":"add","steps":["Extra step"]}]}`)
	if err != nil {
		t.Fatalf("revise string step entries should coerce, got error: %v", err)
	}
	st, _ := store.Snapshot()
	found := false
	for _, s := range st.Steps {
		if s.Title == "Extra step" && s.ID != "" {
			found = true
		}
	}
	if !found {
		t.Errorf("coerced revise step missing or without id: %+v", st.Steps)
	}
}

// Review fixes: presence-based ambiguity gate — steps:[] plus a competing
// array is a conflict; wrapper alongside top-level steps is a conflict.
func TestPlanReviewFixes_AmbiguityGates(t *testing.T) {
	store := NewPlanStore(12, 4000)
	if _, err := store.Execute(`{"verb":"create","steps":[],"operations":[{"id":"x","title":"X"}]}`); err == nil {
		t.Error("empty steps + competing array must be rejected as ambiguous")
	}
	if _, err := store.Execute(`{"verb":"create","steps":[{"id":"a","title":"A"}],"create":{"steps":[{"id":"b","title":"B"}]}}`); err == nil {
		t.Error("top-level steps + wrapper steps must be rejected as ambiguous")
	}
}

// Review fix: diagnostic key echo is bounded — hostile oversized keys cannot
// flood the context through a rejection message.
func TestPlanReviewFixes_BoundedKeyEcho(t *testing.T) {
	store := NewPlanStore(12, 4000)
	bigKey := strings.Repeat("k", 500)
	_, err := store.Execute(`{"verb":"create","` + bigKey + `":[{"id":"x","title":"X"}]}`)
	if err == nil {
		t.Fatal("expected error")
	}
	if len(err.Error()) > 400 {
		t.Errorf("diagnostic must be bounded, got %d chars: %s", len(err.Error()), err.Error())
	}
}

// Review fix: trimmed-id dedupe — " s1" and an auto-assigned s1 must not
// both pass into the plan.
func TestPlanReviewFixes_TrimmedIDDedupe(t *testing.T) {
	store := NewPlanStore(12, 4000)
	_, err := store.Execute(`{"verb":"create","steps":[{"id":" s1","title":"A"},{"title":"B"}]}`)
	if err != nil {
		t.Fatalf("expected acceptance with dedupe-safe auto id, got: %v", err)
	}
	st, _ := store.Snapshot()
	ids := map[string]bool{}
	for _, s := range st.Steps {
		if ids[s.ID] {
			t.Errorf("duplicate id %q after trim+auto-assign", s.ID)
		}
		ids[s.ID] = true
	}
}

// Guards: coercion must not weaken existing validation.
func TestPlanResilience_ExistingValidationIntact(t *testing.T) {
	store := NewPlanStore(12, 4000)
	if _, err := store.Execute(`{"verb":"create","steps":[]}`); err == nil {
		t.Error("empty steps array must still be rejected")
	}
	if _, err := store.Execute(`{"verb":"create","steps":[{"id":"s1","title":""}]}`); err == nil {
		t.Error("empty title must still be rejected")
	}
	var raw json.RawMessage
	_ = raw
}
