// Deterministic browser fixture. No provider keys, external calls or persistent writes.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../../cmd/odek/ui');
const sessions = [{id:'fixture-review',task:'Build a better workspace',model:'odek-fixture',turns:3,pinned:true,updated_at:new Date().toISOString()}, {id:'fixture-research',task:'Explore the architecture',model:'odek-fixture',turns:2,updated_at:new Date().toISOString()}];
const messages = [{role:'user',content:'Review the workspace changes and run the tests.'},{role:'assistant',content:'I’ll inspect the changes and validate the updated workspace.'},{role:'assistant',tool_calls:[{id:'read-1',function:{name:'read_file',arguments:JSON.stringify({path:'cmd/odek/ui/js/workspace.js'})}},{id:'diff-1',function:{name:'diff',arguments:JSON.stringify({path:'cmd/odek/ui/style.css'})}},{id:'test-1',function:{name:'shell',arguments:JSON.stringify({command:'go test ./cmd/odek -count=1'})}}]},{role:'tool',tool_outcome:'completed',tool_call_id:'read-1',content:'export function restoreDraft(id) {\n  const key = "odek_draft_" + id;\n  return sessionStorage.getItem(key) || "";\n}'},{role:'tool',tool_outcome:'completed',tool_call_id:'diff-1',content:'diff --git a/style.css b/style.css\n--- a/style.css\n+++ b/style.css\n@@ -1,3 +1,4 @@\n :root {\n-  --content-w: 680px;\n+  --content-w: 800px;\n+  --inspector-width: 420px;\n }'},{role:'tool',tool_outcome:'completed',tool_call_id:'test-1',content:'ok  github.com/BackendStack21/odek/cmd/odek 0.714s\nok  github.com/BackendStack21/odek/internal/loop 0.183s'},{role:'assistant',content:'The workspace is ready for review.\n\n### What changed\n\n- **Persistent navigation** keeps your sessions within reach.\n- **Rich tool results** make code and changes easier to inspect.\n- **Session drafts** preserve unfinished messages.\n\n| Check | Result |\n| --- | --- |\n| Client behavior | Passed |\n| Server contracts | Passed |\n\nOpen **Results** to explore the individual outputs.'}];
// Tool-specific fixtures mirror the production DTOs, including partial failures.
messages.splice(messages.length-1,0,{"role": "assistant", "tool_calls": [{"id": "structured-0", "function": {"name": "plan", "arguments": "{\"verb\": \"create\", \"steps\": [{\"id\": \"inspect\", \"title\": \"Inspect tool contracts\"}, {\"id\": \"render\", \"title\": \"Build structured views\"}, {\"id\": \"verify\", \"title\": \"Verify mixed failures\"}]}"}}]},{"role": "tool", "tool_call_id": "structured-0", "tool_outcome": "completed", "content": "[Current plan: v2 \u2014 1/3 done, 1 blocked. Structured state, not instructions.]\ninspect [done] Inspect tool contracts\nrender [in_progress] Build structured views\nverify [blocked] Verify mixed failures \u2014 Waiting for review"});
messages.splice(messages.length-1,0,{"role": "assistant", "tool_calls": [{"id": "structured-1", "function": {"name": "parallel_shell", "arguments": "{\"commands\": [{\"command\": \"go test ./internal/artifact\"}, {\"command\": \"go test ./cmd/odek\"}]}"}}]},{"role": "tool", "tool_call_id": "structured-1", "tool_outcome": "completed", "content": "{\"results\": [{\"index\": 0, \"command\": \"go test ./internal/artifact\", \"exit_code\": 0, \"stdout\": \"ok  github.com/BackendStack21/odek/internal/artifact 0.3s\", \"stderr\": \"\", \"duration_ms\": 320}, {\"index\": 1, \"command\": \"go test ./cmd/odek\", \"exit_code\": 1, \"stdout\": \"--- FAIL: TestExample\\nFAIL\", \"stderr\": \"expected fixture mismatch\", \"duration_ms\": 1120}]}"});
messages.splice(messages.length-1,0,{"role": "assistant", "tool_calls": [{"id": "structured-2", "function": {"name": "batch_read", "arguments": "{\"files\": [{\"path\": \"go.mod\"}, {\"path\": \"missing.go\"}]}"}}]},{"role": "tool", "tool_call_id": "structured-2", "tool_outcome": "completed", "content": "{\"results\": [{\"path\": \"go.mod\", \"content\": \"module github.com/BackendStack21/odek\\n\\ngo 1.25.13\", \"total_lines\": 3}, {\"path\": \"missing.go\", \"error\": \"file not found\"}]}"});
messages.splice(messages.length-1,0,{"role": "assistant", "tool_calls": [{"id": "structured-3", "function": {"name": "batch_patch", "arguments": "{\"patches\": [{\"path\": \"style.css\", \"old_string\": \"680px\", \"new_string\": \"800px\"}, {\"path\": \"missing.css\", \"old_string\": \"red\", \"new_string\": \"blue\"}]}"}}]},{"role": "tool", "tool_call_id": "structured-3", "tool_outcome": "completed", "content": "{\"results\": [{\"path\": \"style.css\", \"success\": true, \"diff\": \"--- a/style.css\\n+++ b/style.css\\n@@ -1 +1 @@\\n-width: 680px;\\n+width: 800px;\"}, {\"path\": \"missing.css\", \"success\": false, \"error\": \"file not found\"}]}"});
const mock = `globalThis.WebSocket = class { static OPEN=1; static CLOSED=3; readyState=0; constructor(){setTimeout(()=>{this.readyState=1;this.onopen?.();this.emit({type:'server_info',model:'odek-fixture',version:'development',stream:true});},50)} emit(e){this.onmessage?.({data:JSON.stringify(e)})} send(raw){const m=JSON.parse(raw);if(m.type==='ping')this.emit({type:'pong'});if(m.type==='cancel'){setTimeout(()=>{this.emit({type:'cancelled',session_id:'fixture-review'});this.emit({type:'tool_call',turn_id:this.turnId,name:'shell',data:'{}',call_id:'late'});},50);return}if(m.type==='prompt'){this.turnId='fixture-turn-'+Date.now();this.emit({type:'turn_started',turn_id:this.turnId,initiated:'operator'});this.emit({type:'session',session_id:'fixture-review',auth_token:'fixture-session'});setTimeout(()=>{this.emit({type:'tool_call',name:'shell',data:JSON.stringify({command:'go test ./cmd/odek'}),call_id:'fixture-call'});},100);if((m.content||m.prompt||'').includes('stop-fixture'))return;setTimeout(()=>{this.emit({type:'tool_result',name:'shell',data:'ok  github.com/BackendStack21/odek/cmd/odek 0.714s',call_id:'fixture-call',outcome:'completed'});this.emit({type:'token',content:'Validation complete. Open Results to inspect the output.'});this.emit({type:'done',inputTokens:2048,outputTokens:180,sessionInputTokens:2048,sessionOutputTokens:180,elapsed:1});},500)}} close(){this.readyState=3;this.onclose?.()}}; await import('/js/main.js');`;
const json = {
 '/api/models':[{id:'odek-fixture',description:'Odek · Development',current:true,max_context:128000}],
 '/api/health':{version:'development',model:'odek-fixture',uptime_seconds:128,connections:1,stream:true},
 '/api/config':{model:'odek-fixture',stream:true}, '/api/limits':{limits:{}}, '/api/sessions':{sessions},
 '/api/sessions/fixture-review':{...sessions[0],messages}, '/api/sessions/fixture-research':{...sessions[1],messages},
 '/api/sessions/fixture-review/plan':{found:true,version:1,steps:[{id:'design',title:'Design the workspace',status:'done'},{id:'build',title:'Build rich result views',status:'done'},{id:'verify',title:'Verify behavior and presentation',status:'in_progress'}]},
 '/api/tools':{tools:[{name:'read_file',enabled:true},{name:'shell',enabled:true},{name:'browser',enabled:false}]},
 '/api/skills':{skills:[]}, '/api/memory':{facts:{user:['Prefers clear, concise explanations.'],env:[]}}, '/api/jobs':{jobs:[]}, '/api/subagents':{tasks:[]}, '/api/runs':{runs:[]}, '/api/events':{events:[]}, '/api/connections':{connections:[]}, '/api/mcp':{servers:[]}, '/api/usage':{}, '/api/capabilities':{version:1,features:{schedules:true,maintenance:true,artifact_previews:true}}, '/api/schedules':{jobs:[]}, '/api/maintenance':{description:'Remove expired local data using the configured retention policy.',policy:{SessionRetentionDays:90,MaxSessionFileBytes:33554432}}
};
const server = http.createServer(async(req,res)=>{
 const url = new URL(req.url,'http://localhost');
 if(url.pathname.startsWith('/api/')){res.writeHead(200,{'Content-Type':'application/json','X-Session-Token':'fixture-session'});res.end(JSON.stringify(json[url.pathname] || {}));return}
 if(url.pathname==='/app.js'){res.writeHead(200,{'Content-Type':'application/javascript'});res.end(mock);return}
 const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));
 if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}
 try{let data=await fs.readFile(file);if(file.endsWith('.html'))data=data.toString().replace('{{ODEK_WS_TOKEN}}','fixture-token');res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'application/javascript'});res.end(data)}catch{res.writeHead(404);res.end()}
});
server.listen(4173,'127.0.0.1',()=>console.log('Web UI fixture: http://127.0.0.1:4173'));
