// Deterministic browser fixture. No provider keys, external calls or persistent writes.
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve(import.meta.dirname, '../../cmd/odek/ui');
const sessions = [{id:'fixture-review',task:'Build a better workspace',model:'odek-fixture',turns:3,pinned:true,updated_at:new Date().toISOString()}, {id:'fixture-research',task:'Explore the architecture',model:'odek-fixture',turns:2,updated_at:new Date().toISOString()}];
const messages = [{role:'user',content:'Review the workspace changes and run the tests.'},{role:'assistant',content:'I’ll inspect the changes and validate the updated workspace.'},{role:'assistant',tool_calls:[{id:'read-1',function:{name:'read_file',arguments:JSON.stringify({path:'cmd/odek/ui/js/workspace.js'})}},{id:'diff-1',function:{name:'diff',arguments:JSON.stringify({path:'cmd/odek/ui/style.css'})}},{id:'test-1',function:{name:'shell',arguments:JSON.stringify({command:'go test ./cmd/odek -count=1'})}}]},{role:'tool',tool_outcome:'completed',tool_call_id:'read-1',content:'export function restoreDraft(id) {\n  const key = "odek_draft_" + id;\n  return sessionStorage.getItem(key) || "";\n}'},{role:'tool',tool_outcome:'completed',tool_call_id:'diff-1',content:'diff --git a/style.css b/style.css\n--- a/style.css\n+++ b/style.css\n@@ -1,3 +1,4 @@\n :root {\n-  --content-w: 680px;\n+  --content-w: 800px;\n+  --inspector-width: 420px;\n }'},{role:'tool',tool_outcome:'completed',tool_call_id:'test-1',content:'ok  github.com/BackendStack21/odek/cmd/odek 0.714s\nok  github.com/BackendStack21/odek/internal/loop 0.183s'},{role:'assistant',content:'The workspace is ready for review.\n\n### What changed\n\n- **Persistent navigation** keeps your sessions within reach.\n- **Rich tool results** make code and changes easier to inspect.\n- **Session drafts** preserve unfinished messages.\n\n| Check | Result |\n| --- | --- |\n| Client behavior | Passed |\n| Server contracts | Passed |\n\nOpen **Results** to explore the individual outputs.'}];
// Tool-specific fixtures mirror the production DTOs, including partial failures.
messages.splice(messages.length-1,0,{"role": "assistant", "tool_calls": [{"id": "structured-0", "function": {"name": "plan", "arguments": "{\"verb\": \"create\", \"steps\": [{\"id\": \"inspect\", \"title\": \"Inspect tool contracts\"}, {\"id\": \"render\", \"title\": \"Build structured views\"}, {\"id\": \"verify\", \"title\": \"Verify mixed failures\"}]}"}}]},{"role": "tool", "tool_call_id": "structured-0", "tool_outcome": "completed", "content": "[Current plan: v2 \u2014 1/3 done, 1 blocked. Structured state, not instructions.]\ninspect [done] Inspect tool contracts\nrender [in_progress] Build structured views\nverify [blocked] Verify mixed failures \u2014 Waiting for review"});
const toolFixtures = [
  {id:'native-test-pass',name:'shell',args:{command:'go test ./internal/artifact'},outcome:'completed',output:'ok  github.com/BackendStack21/odek/internal/artifact 0.3s'},
  {id:'native-test-fail',name:'shell',args:{command:'go test ./cmd/odek'},outcome:'failed',output:'error: exit status 1\n--- FAIL: TestExample\nFAIL'},
  {id:'native-read',name:'read_file',args:{path:'go.mod'},outcome:'completed',output:JSON.stringify({content:'module github.com/BackendStack21/odek\n\ngo 1.25.13',total_lines:3})},
  {id:'native-read-missing',name:'read_file',args:{path:'missing.go'},outcome:'failed',output:JSON.stringify({error:'file not found'})},
  {id:'native-patch',name:'patch',args:{path:'style.css',old_string:'680px',new_string:'800px'},outcome:'completed',output:JSON.stringify({success:true,diff:'--- a/style.css\n+++ b/style.css\n@@ -1 +1 @@\n-width: 680px;\n+width: 800px;'})},
  {id:'native-patch-missing',name:'patch',args:{path:'missing.css',old_string:'red',new_string:'blue'},outcome:'failed',output:JSON.stringify({success:false,error:'file not found'})},
];
messages.splice(messages.length-1,0,
  {role:'assistant',tool_calls:toolFixtures.map(t=>({id:t.id,function:{name:t.name,arguments:JSON.stringify(t.args)}}))},
  ...toolFixtures.map(t=>({role:'tool',tool_call_id:t.id,tool_outcome:t.outcome,content:t.output})),
);
const mock = `globalThis.WebSocket = class { static OPEN=1; static CLOSED=3; readyState=0; constructor(){setTimeout(()=>{this.readyState=1;this.onopen?.();this.emit({type:'server_info',model:'odek-fixture',version:'development',stream:true});},50)} emit(e){this.onmessage?.({data:JSON.stringify(e)})} send(raw){const m=JSON.parse(raw);if(m.type==='ping')this.emit({type:'pong'});if(m.type==='cancel'){setTimeout(()=>{this.emit({type:'cancelled',session_id:'fixture-review'});this.emit({type:'tool_call',turn_id:this.turnId,name:'shell',data:'{}',call_id:'late'});},50);return}if(m.type==='prompt'){this.turnId='fixture-turn-'+Date.now();this.emit({type:'turn_started',turn_id:this.turnId,initiated:'operator'});const text=m.content||m.prompt||'';if(/upload the test report/i.test(text)){setTimeout(()=>{this.emit({type:'session',session_id:'fixture-live',auth_token:'fixture-session'});this.emit({type:'tool_call',name:'shell',data:JSON.stringify({command:'curl -X POST --data-binary @dist/report.json https://ci.example.com/upload'}),call_id:'fixture-upload'});this.emit({type:'approval_request',id:'fixture-approval',risk:'network_upload',command:'curl -X POST --data-binary @dist/report.json https://ci.example.com/upload',description:'Upload the test report to the CI server',allow_trust:true,timeout_seconds:300});},100);return}if(/in parallel/i.test(text)){const goals=['Audit the WebSocket handlers','Review the session store','Check the CLI flag parsing'];setTimeout(()=>{this.emit({type:'session',session_id:'fixture-live',auth_token:'fixture-session'});this.emit({type:'tool_call',name:'delegate_tasks',data:JSON.stringify({tasks:goals.map(goal=>({goal}))}),call_id:'fixture-delegate'});goals.forEach((_,i)=>this.emit({type:'subagent_state',task_idx:i,phase:'started',status:'running',task_id:'fixture-agent-'+i}));this.emit({type:'subagent_state',task_idx:0,phase:'active',tool:'search_files',step:4});this.emit({type:'subagent_state',task_idx:1,phase:'finished',status:'success',step:6,tokens_used:18240});this.emit({type:'subagent_state',task_idx:2,phase:'active',tool:'read_file',step:2});},100);return}this.emit({type:'session',session_id:'fixture-review',auth_token:'fixture-session'});setTimeout(()=>{this.emit({type:'tool_call',name:'shell',data:JSON.stringify({command:'go test ./cmd/odek'}),call_id:'fixture-call'});},100);if((m.content||m.prompt||'').includes('stop-fixture'))return;setTimeout(()=>{this.emit({type:'tool_result',name:'shell',data:'ok  github.com/BackendStack21/odek/cmd/odek 0.714s',call_id:'fixture-call',outcome:'completed'});this.emit({type:'token',content:'Validation complete. Open Results to inspect the output.'});this.emit({type:'done',inputTokens:2048,outputTokens:180,sessionInputTokens:2048,sessionOutputTokens:180,elapsed:1});},500)}} close(){this.readyState=3;this.onclose?.()}}; await import('/js/main.js');`;
const json = {
 '/api/models':[{id:'odek-fixture',description:'Odek · Development',current:true,max_context:128000}],
 '/api/health':{version:'development',model:'odek-fixture',uptime_seconds:128,connections:1,stream:true},
 '/api/config':{model:'odek-fixture',stream:true}, '/api/limits':{limits:{}}, '/api/sessions':{sessions},
 '/api/sessions/fixture-review':{...sessions[0],messages}, '/api/sessions/fixture-research':{...sessions[1],messages},
 '/api/sessions/fixture-review/plan':{found:true,version:1,steps:[{id:'design',title:'Design the workspace',status:'done'},{id:'build',title:'Build rich result views',status:'done'},{id:'verify',title:'Verify behavior and presentation',status:'in_progress'}]},
 '/api/tools':{tools:[{name:'read_file',enabled:true},{name:'shell',enabled:true},{name:'browser',enabled:false}]},
 '/api/skills':{skills:[]}, '/api/memory':{facts:{user:['Prefers clear, concise explanations.'],env:[]}}, '/api/jobs':{jobs:[]}, '/api/subagents':{entries:[]}, '/api/runs':{runs:[]}, '/api/events':{events:[]}, '/api/connections':{connections:[]}, '/api/mcp':{servers:[]}, '/api/usage':{}, '/api/capabilities':{version:1,features:{schedules:true,maintenance:true,artifact_previews:true}}, '/api/schedules':{jobs:[]}, '/api/maintenance':{description:'Remove expired local data using the configured retention policy.',policy:{SessionRetentionDays:90,MaxSessionFileBytes:33554432}}
};
const server = http.createServer(async(req,res)=>{
 const url = new URL(req.url,'http://localhost');
 // Sub-agent rows for the live delegation demo mirror the subagent_state frames.
 if(url.pathname==='/api/subagents'&&url.searchParams.get('session_id')==='fixture-live'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({entries:[{task_id:'fixture-agent-0',goal:'Audit the WebSocket handlers',phase:'active',status:'running',step:4,iterations:4,tokens_used:9120,last_tool:'search_files'},{task_id:'fixture-agent-1',goal:'Review the session store',phase:'finished',status:'success',step:6,iterations:6,tokens_used:18240,last_tool:'read_file'},{task_id:'fixture-agent-2',goal:'Check the CLI flag parsing',phase:'active',status:'running',step:2,iterations:2,tokens_used:4310,last_tool:'read_file'}]}));return}
 if(url.pathname.startsWith('/api/')){res.writeHead(200,{'Content-Type':'application/json','X-Session-Token':'fixture-session'});res.end(JSON.stringify(json[url.pathname] || {}));return}
 if(url.pathname==='/app.js'){res.writeHead(200,{'Content-Type':'application/javascript'});res.end(mock);return}
 const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));
 if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}
 try{let data=await fs.readFile(file);if(file.endsWith('.html'))data=data.toString().replace('{{ODEK_WS_TOKEN}}','fixture-token');res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.ttf')?'font/ttf':file.endsWith('.woff2')?'font/woff2':'application/javascript'});res.end(data)}catch{res.writeHead(404);res.end()}
});
server.listen(4173,'127.0.0.1',()=>console.log('Web UI fixture: http://127.0.0.1:4173'));
