// Package skills implements odek's skill system — just-in-time agent specialization.
//
// Skills are structured markdown files (SKILL.md) with YAML frontmatter that
// provide domain knowledge. They load on demand when the user's input matches
// topic/action keywords, keeping the agent's context focused.
//
// Storage layers (lowest → highest priority):
//
//	~/.odek/skills/<name>/SKILL.md      ← user-global (self-improvement writes here)
//	./.odek/skills/<name>/SKILL.md      ← project (committed, shared)
//
// Skills can also be imported from URIs (file:// or https://) via odek skill import.
// The import flow includes an LLM risk assessment and user approval before saving.
package skills

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/BackendStack21/odek/internal/embedding"
)

// ── Types ──────────────────────────────────────────────────────────────

// SkillQuality represents the curation state of a skill.
type SkillQuality string

const (
	QualityDraft    SkillQuality = "draft"    // auto-generated by self-improvement
	QualityVerified SkillQuality = "verified" // passed quality gate + user approved
	QualityImported SkillQuality = "imported" // imported from URI with LLM risk assessment
	QualityManual   SkillQuality = "manual"   // user-created via odek skill save
	QualityStale    SkillQuality = "stale"    // >90 days without use (skipped at load)
)

// SkillTrigger defines when a skill should be loaded into context.
// Skills load when any topic keyword AND any action keyword match the user's input.
type SkillTrigger struct {
	TopicKeywords  []string `json:"topic,omitempty" yaml:"topic,omitempty"`
	ActionKeywords []string `json:"action,omitempty" yaml:"action,omitempty"`
}

// Skill represents a single skill file loaded from a skill directory.
// The struct is populated from the YAML frontmatter plus synthetic fields.
type Skill struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Version     string          `json:"version,omitempty"`
	Author      string          `json:"author,omitempty"`
	Trigger     SkillTrigger    `json:"trigger"`
	AutoLoad    bool            `json:"auto_load"`
	Quality     SkillQuality    `json:"quality"`
	UsageCount  int             `json:"usage_count"`
	LastUsed    time.Time       `json:"last_used"`
	Body        string          `json:"body"`           // raw markdown body (no frontmatter)
	BodyHash    string          `json:"body_hash"`      // sha256 of body (for dedup)
	Source      SkillSource     `json:"source"`         // where the skill came from
	Provenance  SkillProvenance `json:"provenance"`     // trust signals for the originating session
	Meta        map[string]any  `json:"meta,omitempty"` // arbitrary extra frontmatter fields
}

// SkillSource identifies where a skill was loaded from.
type SkillSource struct {
	Dir  string `json:"dir"`  // e.g. "~/.odek/skills" or "./.odek/skills"
	Path string `json:"path"` // full path to SKILL.md
}

// SkillProvenance captures the trust signals of the session that
// produced the skill. Set by the auto-save flow when the originating
// session touched external (untrusted) content — fetched pages, files
// outside CWD, or other tools that returned attacker-controllable data.
// A non-empty Sources list combined with Untrusted=true should suppress
// auto-activation and require explicit user promotion.
type SkillProvenance struct {
	// Untrusted is true when the originating session ingested external
	// content (browser fetch, read_file outside CWD, MCP tool with
	// untrusted source, etc.). Auto-save and auto-load policies should
	// treat such skills as needing explicit user review.
	Untrusted bool `json:"untrusted"`
	// Sources lists the external resources the originating session
	// touched, for user review. Empty for trusted skills.
	Sources []string `json:"sources,omitempty"`
	// NeedsReview is true when the user has not yet promoted this skill.
	// Defaults to true for any auto-saved skill so the first activation
	// goes through a confirmation prompt.
	NeedsReview bool `json:"needs_review"`
}

// SkillsConfig holds the skills section of odek.json.
type SkillsConfig struct {
	MaxAutoLoad  int            `json:"max_auto_load"`
	MaxLazySlots int            `json:"max_lazy_slots"`
	Learn        bool           `json:"learn"`
	Dirs         []string       `json:"dirs,omitempty"`
	Import       ImportConfig   `json:"import"`
	Curation     CurationConfig `json:"curation"`
	AutoSave     AutoSaveConfig `json:"auto_save"`
	LLMLearn     bool           `json:"llm_learn"`
	LLMCurate    bool           `json:"llm_curate"`
	Verbose      bool           `json:"verbose"` // show full skill banners when loaded

	// Embedding opts skill matching into a remote (HTTP) embedding backend for
	// real semantic matching. nil (default) = local RandomProjections. It is
	// NOT inherited from the top-level embedding default because skill matching
	// runs on every turn — opt in explicitly. See internal/embedding.Config.
	Embedding *embedding.Config `json:"embedding,omitempty"`
}

// ImportConfig controls the URI import flow.
type ImportConfig struct {
	MaxSizeBytes int  `json:"max_size_bytes"`
	TimeoutSecs  int  `json:"timeout_seconds"`
	RequireHTTPS bool `json:"require_https"`
}

// CurationConfig controls automated curation.
type CurationConfig struct {
	StalenessDays int  `json:"staleness_days"`
	AutoPrune     bool `json:"auto_prune"`
	AutoCurate    bool `json:"auto_curate"`
	SkipThreshold int  `json:"skip_threshold"`
	SkipResetDays int  `json:"skip_reset_days"`
}

// AutoSaveConfig controls automatic skill saving behavior.
type AutoSaveConfig struct {
	Enabled    bool `json:"enabled"`
	RequireLLM bool `json:"require_llm"`
	MaxPerRun  int  `json:"max_per_run"`
}

// DefaultSkillsConfig returns sensible defaults for the skills system.
func DefaultSkillsConfig() SkillsConfig {
	return SkillsConfig{
		MaxAutoLoad:  3,
		MaxLazySlots: 5,
		Learn:        true,
		Dirs:         nil, // computed at runtime
		Import: ImportConfig{
			MaxSizeBytes: 1_048_576, // 1MB
			TimeoutSecs:  5,
			RequireHTTPS: false,
		},
		Curation: CurationConfig{
			StalenessDays: 90,
			AutoPrune:     false,
			AutoCurate:    true,
			SkipThreshold: 3,
			SkipResetDays: 30,
		},
		AutoSave: AutoSaveConfig{
			Enabled:    true,
			RequireLLM: true,
			MaxPerRun:  3,
		},
		LLMLearn:  true,
		LLMCurate: true,
		Verbose:   false,
	}
}

// ── Skip List ────────────────────────────────────────────────────────

// SkippedEntry records a skill suggestion that the user chose to skip.
type SkippedEntry struct {
	SkippedAt    time.Time `json:"skipped_at"`
	Heuristic    string    `json:"heuristic"`
	TimesSkipped int       `json:"times_skipped"`
}

// SkipList is the persistent record of skipped skill suggestions.
type SkipList struct {
	Skipped map[string]SkippedEntry `json:"skipped"`
}

// skipListPath returns the path to the skip list file.
func skipListPath(userDir string) string {
	return filepath.Join(userDir, ".skipped.json")
}

// LoadSkipList reads the skip list from disk or returns an empty one.
func LoadSkipList(userDir string) *SkipList {
	sl := &SkipList{Skipped: make(map[string]SkippedEntry)}
	data, err := os.ReadFile(skipListPath(userDir))
	if err != nil {
		return sl
	}
	json.Unmarshal(data, sl)
	if sl.Skipped == nil {
		sl.Skipped = make(map[string]SkippedEntry)
	}
	return sl
}

// SaveSkipList writes the skip list to disk.
func (sl *SkipList) Save(userDir string) error {
	data, err := json.MarshalIndent(sl, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal skip list: %w", err)
	}
	if err := os.MkdirAll(userDir, 0755); err != nil {
		return fmt.Errorf("create skills dir: %w", err)
	}
	return os.WriteFile(skipListPath(userDir), data, 0644)
}

// ShouldSkip returns true if the suggestion should be suppressed.
// A suggestion is skipped if it has been skipped >= threshold times and
// the last skip was within resetDays, OR if it was skipped at all and
// the threshold is 1 (skip-once mode).
func (sl *SkipList) ShouldSkip(name string, threshold, resetDays int) bool {
	entry, ok := sl.Skipped[name]
	if !ok {
		return false
	}
	if threshold <= 1 {
		return true // skip-once: suppress after first skip
	}
	if entry.TimesSkipped >= threshold {
		// Check if the skip has expired
		if resetDays > 0 {
			// Use duration arithmetic instead of AddDate to avoid
			// DST-sensitive behaviour where a "day" isn't always 24 hours.
			expiry := entry.SkippedAt.Add(time.Duration(resetDays) * 24 * time.Hour)
			if time.Now().UTC().After(expiry) {
				// Skip expired, allow re-suggestion
				return false
			}
		}
		return true
	}
	return false
}

// RecordSkip records a skipped suggestion and persists the skip list.
func (sl *SkipList) RecordSkip(userDir, name, heuristic string) error {
	entry := sl.Skipped[name]
	entry.SkippedAt = time.Now().UTC()
	entry.Heuristic = heuristic
	entry.TimesSkipped++
	sl.Skipped[name] = entry
	return sl.Save(userDir)
}

// ClearSkip removes a specific entry from the skip list and persists.
func (sl *SkipList) ClearSkip(userDir, name string) error {
	delete(sl.Skipped, name)
	return sl.Save(userDir)
}

// ClearAllSkips removes all entries and persists.
func (sl *SkipList) ClearAllSkips(userDir string) error {
	sl.Skipped = make(map[string]SkippedEntry)
	return sl.Save(userDir)
}

// FilterSkipped removes suggestions that should be skipped from a slice.
// Returns the filtered slice and the number that were filtered out.
func FilterSkipped(suggestions []SkillSuggestion, userDir string, threshold, resetDays int) ([]SkillSuggestion, int) {
	sl := LoadSkipList(userDir)
	filtered := make([]SkillSuggestion, 0, len(suggestions))
	skipped := 0
	for _, s := range suggestions {
		if sl.ShouldSkip(s.Name, threshold, resetDays) {
			skipped++
			continue
		}
		filtered = append(filtered, s)
	}
	return filtered, skipped
}

// ── Default Skill Dirs ────────────────────────────────────────────────

// UserSkillsDir returns ~/.odek/skills/
func UserSkillsDir() string { return "~/.odek/skills" }

// ProjectSkillsDir returns ./.odek/skills/
func ProjectSkillsDir() string { return "./.odek/skills" }

// ── Helpers ────────────────────────────────────────────────────────────

// ValidateSkillName checks that a skill name is safe for filesystem use.
// Returns an error if the name contains path separators, relative components,
// or hidden-file prefixes.
func ValidateSkillName(name string) error {
	if name == "" {
		return fmt.Errorf("skill name is empty")
	}
	if strings.Contains(name, "/") || strings.Contains(name, "\\") {
		return fmt.Errorf("skill name %q contains path separators", name)
	}
	if strings.Contains(name, "..") {
		return fmt.Errorf("skill name %q contains path traversal (..)", name)
	}
	if name == "." || name == ".." {
		return fmt.Errorf("skill name is a relative path (%q)", name)
	}
	if strings.HasPrefix(name, ".") {
		return fmt.Errorf("skill name %q starts with a dot (hidden)", name)
	}
	return nil
}

// HashBody returns a sha256 hex digest of the body text.
func HashBody(body string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(body)))
	return hex.EncodeToString(h[:])
}

// ActiveQualities returns the set of quality states that should be loaded.
func ActiveQualities() map[SkillQuality]bool {
	return map[SkillQuality]bool{
		QualityDraft:    true,
		QualityVerified: true,
		QualityImported: true,
		QualityManual:   true,
	}
}
