// Package skills implements kode's skill system — just-in-time agent specialization.
//
// Skills are structured markdown files (SKILL.md) with YAML frontmatter that
// provide domain knowledge. They load on demand when the user's input matches
// topic/action keywords, keeping the agent's context focused.
//
// Storage layers (lowest → highest priority):
//
//	~/.kode/skills/<name>/SKILL.md      ← user-global (self-improvement writes here)
//	./.kode/skills/<name>/SKILL.md      ← project (committed, shared)
//
// Skills can also be imported from URIs (file:// or https://) via kode skill import.
// The import flow includes an LLM risk assessment and user approval before saving.
package skills

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"time"
)

// ── Types ──────────────────────────────────────────────────────────────

// SkillQuality represents the curation state of a skill.
type SkillQuality string

const (
	QualityDraft     SkillQuality = "draft"     // auto-generated by self-improvement
	QualityVerified  SkillQuality = "verified"  // passed quality gate + user approved
	QualityImported  SkillQuality = "imported"  // imported from URI with LLM risk assessment
	QualityManual    SkillQuality = "manual"    // user-created via kode skill save
	QualityStale     SkillQuality = "stale"     // >90 days without use (skipped at load)
)

// SkillTrigger defines when a skill should be loaded into context.
// Skills load when any topic keyword AND any action keyword match the user's input.
type SkillTrigger struct {
	TopicKeywords  []string `json:"topic,omitempty" yaml:"topic,omitempty"`
	ActionKeywords []string `json:"action,omitempty" yaml:"action,omitempty"`
}

// Skill represents a single skill file loaded from a skill directory.
// The struct is populated from the YAML frontmatter plus synthetic fields.
type Skill struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Version     string        `json:"version,omitempty"`
	Author      string        `json:"author,omitempty"`
	Trigger     SkillTrigger  `json:"trigger"`
	AutoLoad    bool          `json:"auto_load"`
	Quality     SkillQuality  `json:"quality"`
	UsageCount  int           `json:"usage_count"`
	LastUsed    time.Time     `json:"last_used"`
	Body        string        `json:"body"`          // raw markdown body (no frontmatter)
	BodyHash    string        `json:"body_hash"`     // sha256 of body (for dedup)
	Source      SkillSource   `json:"source"`        // where the skill came from
	Meta        map[string]any `json:"meta,omitempty"`// arbitrary extra frontmatter fields
}

// SkillSource identifies where a skill was loaded from.
type SkillSource struct {
	Dir  string `json:"dir"`  // e.g. "~/.kode/skills" or "./.kode/skills"
	Path string `json:"path"` // full path to SKILL.md
}

// SkillsConfig holds the skills section of kode.json.
type SkillsConfig struct {
	MaxAutoLoad  int            `json:"max_auto_load"`
	MaxLazySlots int            `json:"max_lazy_slots"`
	Learn        bool           `json:"learn"`
	Dirs         []string       `json:"dirs,omitempty"`
	Import       ImportConfig   `json:"import"`
	Curation     CurationConfig `json:"curation"`
}

// ImportConfig controls the URI import flow.
type ImportConfig struct {
	MaxSizeBytes  int  `json:"max_size_bytes"`
	TimeoutSecs   int  `json:"timeout_seconds"`
	RequireHTTPS  bool `json:"require_https"`
}

// CurationConfig controls automated curation.
type CurationConfig struct {
	StalenessDays int  `json:"staleness_days"`
	AutoPrune     bool `json:"auto_prune"`
}

// DefaultSkillsConfig returns sensible defaults for the skills system.
func DefaultSkillsConfig() SkillsConfig {
	return SkillsConfig{
		MaxAutoLoad:  3,
		MaxLazySlots: 5,
		Learn:        false,
		Dirs:         nil, // computed at runtime
		Import: ImportConfig{
			MaxSizeBytes: 1_048_576, // 1MB
			TimeoutSecs:  5,
			RequireHTTPS: false,
		},
		Curation: CurationConfig{
			StalenessDays: 90,
			AutoPrune:     false,
		},
	}
}

// ── Default Skill Dirs ────────────────────────────────────────────────

// UserSkillsDir returns ~/.kode/skills/
func UserSkillsDir() string { return "~/.kode/skills" }

// ProjectSkillsDir returns ./.kode/skills/
func ProjectSkillsDir() string { return "./.kode/skills" }

// ── Helpers ────────────────────────────────────────────────────────────

// ValidateSkillName checks that a skill name is safe for filesystem use.
// Returns an error if the name contains path separators, relative components,
// or hidden-file prefixes.
func ValidateSkillName(name string) error {
	if name == "" {
		return fmt.Errorf("skill name is empty")
	}
	if strings.Contains(name, "/") || strings.Contains(name, "\\") {
		return fmt.Errorf("skill name %q contains path separators", name)
	}
	if strings.Contains(name, "..") {
		return fmt.Errorf("skill name %q contains path traversal (..)", name)
	}
	if name == "." || name == ".." {
		return fmt.Errorf("skill name is a relative path (%q)", name)
	}
	if strings.HasPrefix(name, ".") {
		return fmt.Errorf("skill name %q starts with a dot (hidden)", name)
	}
	return nil
}

// HashBody returns a sha256 hex digest of the body text.
func HashBody(body string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(body)))
	return hex.EncodeToString(h[:])
}

// ActiveQualities returns the set of quality states that should be loaded.
func ActiveQualities() map[SkillQuality]bool {
	return map[SkillQuality]bool{
		QualityDraft:    true,
		QualityVerified: true,
		QualityImported: true,
		QualityManual:   true,
	}
}
